trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: PowerShell@2
  displayName: 'Extract All ZIPs to Current Directory'
  inputs:
    targetType: 'inline'
    script: |
      $destinationPath = "$(Build.SourcesDirectory)"

      # Load .NET Zip extraction library
      Add-Type -AssemblyName System.IO.Compression.FileSystem

      # Get all .zip files in the current directory
      $zipFiles = Get-ChildItem -Path $destinationPath -Filter "*.zip"

      foreach ($zipFile in $zipFiles) {
          Write-Host "Extracting: $($zipFile.FullName)"
          [System.IO.Compression.ZipFile]::ExtractToDirectory($zipFile.FullName, $destinationPath, $true)
      }

      Write-Host "All zip files extracted to: $destinationPath"

- task: QualysIaCSecurityConnector@2
  inputs:
    failByCriticalStatus: true
    critical: '2'
    failByHighStatus: true
    high: '2'
    failByMediumStatus: true
    medium: '2'
    failByLowStatus: true
    low: '2'
    IacService: 'USPod02-IaCServiceConnection'
  displayName: 'Qualys IaC Security Scan'
