trigger:
- main
 
pool:
  vmImage: ubuntu-latest
 
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
 
- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
 
- task: QualysIaCSecurityConnector@2
  inputs:
    failByCriticalStatus: true
    critical: '2'
    failByHighStatus: true
    high: '2'
    failByMediumStatus: true
    medium: '2'
    failByLowStatus: true
    low: '2'
    IacService: 'USPod01-IaCServiceConnection'
  displayName: 'Qualys IaC Security Scan'